config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  
  
  
  root 'home#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  
    validates_presence_of :razaosocial, :nomefantasia, :tipo, :documento, :telefone
    validates_uniqueness_of :documento
    
    validate :formato_do_documento
    
    private
    
    def formato_do_documento
      #Validar se o formato do documento confere com CNPJ ou CPF
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente foi excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:razaosocial, :nomefantasia, :tipo, :documento, :telefone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
   

end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag( :span, model.errors[attribute].first, class: 'error_message' )
    end
  end

  def attribute_has_error?(model, attribute)
    (model.errors.has_key? attribute)
  end

  def form_input_error_class(model, attribute)
    if attribute_has_error?(model, attribute)
      "has-error"
    end
  end

  def form_text_input_field(form, model, attribute)
    content_tag(:div, :class => "form-group  #{form_input_error_class(model, attribute)}") do
      (form.label attribute, :class => "col-lg-full control-label") << 
      (form.text_field attribute, :class => "form-control")
    end
  end

  def form_submit_button(form)
    (form.submit "", type: "image", class: "glyphicon glyphicon-ok")
  end

  def data_table(models, attributes = [])

    content_tag(:table, :class => "table table-striped table-hover") do
      (content_tag(:thead) do
        content_tag :tr do
          header = attributes.collect { |attribute|
            concat content_tag(:th, (t ".#{attribute}"))
          }
          header[0] << (content_tag(:th, 'Ações'))
          header.to_s.html_safe
        end
      end) <<
      (content_tag :tbody do
        models.collect { |model|
          concat (content_tag :tr do
             count = 0
             line = attributes.collect { |attribute|
               count += count+1
               if count == 1
                 concat content_tag :td, ((show_button(model, (t model[attributes.first]))))
               else
                 concat content_tag :td, (model[attribute])
               end
             }
             line[0] << (content_tag :td, (((edit_button(model)) << remove_button(model))))
             line
          end)
        }.to_s.html_safe
      end)
    end
  end

  def link_button(label, path)
    (link_to (t ".#{label}"), path, :class => "btn btn-info")
  end
  
  def icon_link_button(path, css_class)
    (link_to path do
      (content_tag :i, "",  :class => css_class)
    end)
  end

  def back_button(label = 'links.voltar', path)
    (link_to path do
      (content_tag :i, "",  :class => "glyphicon glyphicon-arrow-left")
    end)
  end

  def show_button(path, label = 'links.mostrar')
    (link_to label, path)
  end

  def edit_button(model, label = 'links.editar')
    (link_to send(("edit_#{model.class.name.downcase}_path"), model) do
      (content_tag :i, "",  :class => "glyphicon glyphicon-edit")
    end)
  end

  def remove_button(model, label = 'links.apagar')
    (link_to model, method: :delete, data: { confirm: "Tem certeza que dseja exluir o registro?" } do
      (content_tag :i, "",  :class => "glyphicon glyphicon-remove")
    end)
  end

  def show_header(header_message_nome_param)
    content_tag(:div, :class => "panel-heading") do
      content_tag(:h2, :class => "panel-title show-title") do
        (t ".perfil", nome: header_message_nome_param)
      end
    end
  end

  def show_full_row(model, attribute)
    content_tag(:div, :class => "row") do
      content_tag(:div, :class => "full-cell") do
        show_field(model, attribute)
      end
    end
  end

  def show_body()
    content_tag(:div, :class => "panel-body") do
      yield if block_given?
    end
  end

  def show_two_column_row(model_row_one, attribute_row_one, model_row_two, attribute_row_two)
    content_tag(:div, :class => "row") do
      show_column_row(model_row_one, attribute_row_one) <<
      show_column_row(model_row_two, attribute_row_two)
    end
  end

  def show_column_row(model, attribute)
    content_tag(:div, :class => "cell") do
      show_field(model, attribute)
    end
  end

  def show_field(model, attribute)
    content_tag(:span, :class => "label label-default") do
      (t ".#{attribute}")
    end << " ".freeze <<
    (model[attribute])
  end

end

app/views/clientes/_form.html.erb
<div class="row">
	<div class="col-lg-12">
		<div class="box">
			<header>
				<div class="icons">
					<i class="fa fa-th-large"></i>
				</div>
				<h5><%= t '.titulo' %></h5>

				<!-- .toolbar -->
				<div class="toolbar">
					<nav style="padding: 8px;">
						<a href="javascript:;" class="btn btn-default btn-xs full-box"> <i class="fa fa-expand"></i> </a>
					</nav>
				</div><!-- /.toolbar -->
			</header>
			<div id="collapseOne" class="body">
				<%= form_for @cliente, :html => {:class => "form-horizontal", :id => "block-validate"} do |f| %>

				<div class="form-group">
					<label class="control-label col-lg-4"><%= f.label :razaosocial %></label>
					<div class="col-lg-4">
						<%= f.text_field :razaosocial, class:"form-control" %>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4"><%= f.label :nomefantasia %>
						<br>
					</label>
					<div class="col-lg-4">
						<%= f.text_field :nomefantasia, class:"form-control" %>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4"><%= f.label :tipo %>
						<br>
					</label>
					<div class="col-lg-4">
						<%= f.select :tipo, [['Pessoa Física', 'PF'], ['Pessoa Jurídica', 'PJ']], {}, {class: "form-control", onclick: "atualizarDocumento()"} %>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4"><%= f.label :documento %></label>
					<div id="documento" class="col-lg-4">
						<div class="input-group">
							<% if f.object.tipo == 'PJ' %>
								<%= f.text_field :documento, {:class => "form-control", 'data-mask' => "99.999.999/9999-99"} %>
								<%= content_tag :span, '99.999.999/9999-99', class: "input-group-addon" %>
							<% else %>
								<%= f.text_field :documento, {:class => "form-control", 'data-mask' => "999.999.999-99"} %>
								<%= content_tag :span, '999.999.999-99', class: "input-group-addon" %>
							<% end %>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-lg-4"><%= f.label :telefone %></label>
					<div class="col-lg-4">
						<div class="input-group">
							<%= f.text_field :telefone, {:class => "form-control", 'data-mask' => "(99) 99999-9999"} %>
							<%= content_tag :span, '(99) 99999-9999', class: "input-group-addon" %>
						</div>

					</div>
				</div>

				<div class="form-actions no-margin-bottom">
					<%= f.submit class: "btn btn-primary" %>
				</div>

				<% end %>
			</div>
		</div>
	</div><!-- /.col-lg-12 -->
</div><!-- /.row -->

<!--jQuery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-en.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

<script>
	(function($) {
		"use strict";

		Metis.formValidation = function() {

			$('#block-validate').validate({
				rules : {
					"cliente[razaosocial]" : "required",
					"cliente[nomefantasia]" : "required",
					"cliente[tipo]" : "required",
					"cliente[documento]" : "required",
					"cliente[telefone]" : "required",
				},
				errorClass : 'help-block',
				errorElement : 'span',
				highlight : function(element, errorClass, validClass) {
					$(element).parents('.form-group').removeClass('has-success').addClass('has-error');
				},
				unhighlight : function(element, errorClass, validClass) {
					$(element).parents('.form-group').removeClass('has-error').addClass('has-success');
				}
			});
			/*----------- END validate CODE -------------------------*/
		};

		return Metis;
	})(jQuery);
	;
	Metis.formValidation();
	function atualizarDocumento() {
	  	 
	} 
</script>

app/views/clientes/_tools.html.erb
<li>
	<%= icon_link_button "/", "home-button-icon" %>
</li>

<li>
	<%= icon_link_button clientes_path, "list-button-icon" %>
</li>

<li>
	<%= icon_link_button new_cliente_path, "new-button-icon" %>
</li>

<li>
	<%= link_to "#" do %>
	<% (content_tag :i, "",  class: "print-button-icon", onclick: "window.print()")%>
	<%end %>
</li>

app/views/clientes/edit.html.erb
<%= render partial: 'form', locals: {back_path: clientes_path, title: (t '.title')} %>

app/views/clientes/index.html.erb
<div class="row ui-sortable">
	<div class="col-lg-12" style="position: relative;">
		<div class="box">
			<header>
				<div class="icons">
					<i class="fa fa-table"></i>
				</div>
				<h5><%= t ".#{:listagem}" %></h5>
			</header>
			<div id="collapse4" class="body">
				<div id="dataTable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
					<div class="row">
						<div class="col-xs-6">
							<div class="dataTables_length" id="dataTable_length">
								<label><%= t "index.mostrar" %>
									<select name="dataTable_length" aria-controls="dataTable" class="form-control input-sm">
										<option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option>
									</select> <%= t "index.registros" %></label>
							</div>
						</div>
						<div class="col-xs-6">
							<div id="dataTable_filter" class="dataTables_filter">
								<label>Search:
									<input type="search" class="form-control input-sm" placeholder="" aria-controls="dataTable">
								</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12">
							<table id="dataTable" class="table table-bordered table-condensed table-hover table-striped dataTable no-footer" role="grid" aria-describedby="dataTable_info">
								<thead>
									<tr role="row">
										<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending" style="width: 158px;"><%= t ".#{:documento}" %></th>
										<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 197px;"><%= t ".#{:razaosocial}" %></th>
										<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 180px;"><%= t ".#{:nomefantasia}" %></th>
										<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 137px;"><%= t ".#{:tipo}" %></th>
										<th class="sorting_desc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 99px;" aria-sort="descending"><%= t ".#{:telefone}" %></th>
										<th class="sorting_desc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 99px;" aria-sort="descending"><%= t "index.acoes_no_registro" %></th>
									</tr>
								</thead>
								<tbody>
									<% @clientes.each do |cliente| %>

									<tr role="row" >
										<td class=""> <%= cliente.documento %></td>
										<td class=""> <%= cliente.razaosocial %></td>
										<td class=""> <%= cliente.nomefantasia %></td>
										<td class=""> <%= cliente.tipo %></td>
										<td class=""> <%= cliente.telefone %></td>
										<td class=""> <%= link_to edit_cliente_path(cliente)  do %>
										<% (content_tag :i, "",  :class => "glyphicon glyphicon-edit") %>
										<% end %>
										<%= link_to cliente, method: :delete, data: { confirm: "Tem certeza que dseja exluir o registro?" } do  %>
										<% (content_tag :i, "",  :class => "glyphicon glyphicon-remove")  %>
										<%end  %> 
										</td>
									</tr>
									<% end %>
								</tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-6">
							<div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">
								<%= t 'index.quantidade_de_registro', quantidade_inicial: 1, quantidade_final: 10, quantidade_total: @clientes.size %>
							</div>
						</div>
						<div class="col-xs-6">
							<div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
								<ul class="pagination">
									<li class="paginate_button previous disabled" aria-controls="dataTable" tabindex="0" id="dataTable_previous">
										<a href="#">Previous</a>
									</li>
									<li class="paginate_button active" aria-controls="dataTable" tabindex="0">
										<a href="#">1</a>
									</li>
									<li class="paginate_button " aria-controls="dataTable" tabindex="0">
										<a href="#">2</a>
									</li>
									<li class="paginate_button " aria-controls="dataTable" tabindex="0">
										<a href="#">3</a>
									</li>
									<li class="paginate_button " aria-controls="dataTable" tabindex="0">
										<a href="#">4</a>
									</li>
									<li class="paginate_button " aria-controls="dataTable" tabindex="0">
										<a href="#">5</a>
									</li>
									<li class="paginate_button " aria-controls="dataTable" tabindex="0">
										<a href="#">6</a>
									</li>
									<li class="paginate_button next" aria-controls="dataTable" tabindex="0" id="dataTable_next">
										<a href="#">Next</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/clientes/new.html.erb
<%= render partial: 'form', locals: {back_path: clientes_path, title: (t '.title')} %>

app/views/clientes/show.html.erb
<div class="panel panel-index">
	<%= show_header(@cliente.razaosocial) %>
	<%= show_body do %>

	<%= show_full_row @cliente, :razaosocial %>
	<%= show_two_column_row @cliente, :nomefantasia, @cliente, :tipo %>
	<%= show_two_column_row @cliente, :documento, @cliente, :telefone %>

	<%= back_button clientes_path %>
	<%= (edit_button(@cliente)) %>

	<% end %>
</div>

app/views/home/_tools.html.erb
<li>
	<%= icon_link_button "/", "home-button-icon" %>
</li>

<li>
	<%= link_to "#" do %>
	<% (content_tag :i, "",  class: "print-button-icon", onclick: "window.print()")%>
	<%end %>
</li>

app/views/home/index.html.erb
<p>Pagina inicial</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Testox</title>

		<!--IE Compatibility modes-->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<!--Mobile first-->
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/css/bootstrap.min.css">

		<!-- Font Awesome -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css">

		<!-- metisMenu stylesheet -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/metisMenu/1.1.3/metisMenu.min.css">

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

		<!--[if lt IE 9]>
		<script src="assets/lib/html5shiv/html5shiv.js"></script>
		<script src="assets/lib/respond/respond.min.js"></script>
		<![endif]-->

		<!--For Development Only. Not required -->
		<script>
			less = {
				env : "development",
				relativeUrls : false,
				rootpath : "../assets/"
			};
		</script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.2.0/less.min.js"></script>

		<!--Modernizr-->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<!--jQuery -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

		<!--Bootstrap -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>

		<!-- MetisMenu -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/metisMenu/1.1.3/metisMenu.min.js"></script>

		<!-- Screenfull -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/screenfull.js/2.0.0/screenfull.min.js"></script>

		<!-- Validations engine -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.13.1/jquery.validate.min.js"></script>

		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	</head>
	<body class="menu-affix" style="padding-top: 0px; background-image: url(http://demo.onokumus.com/metis/assets/img/pattern/arches.png); background-repeat: repeat;">

		<div class="bg-dark dk" id="wrap">
			<div id="top">

				<!-- .navbar -->
				<nav class="navbar navbar-inverse navbar-static-top">
					<div class="container-fluid">

						<!-- Brand and toggle get grouped for better mobile display -->
						<header class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<%= link_to "/" do %>
							<img width="50%" src="<%= asset_path("logo_novo.png") %>"  />
							<%end %>
						</header>
						<div class="topnav">
							<div class="btn-group">
								<a data-placement="bottom" data-original-title="Fullscreen" data-toggle="tooltip" class="btn btn-default btn-sm" id="toggleFullScreen"> <i class="glyphicon glyphicon-fullscreen"></i> </a>
							</div>
							<div class="btn-group">
								<a data-placement="bottom" data-original-title="E-mail" data-toggle="tooltip" class="btn btn-default btn-sm"> <i class="fa fa-envelope"></i> <span class="label label-warning">5</span> </a>
								<a data-placement="bottom" data-original-title="Messages" href="#" data-toggle="tooltip" class="btn btn-default btn-sm"> <i class="fa fa-comments"></i> <span class="label label-danger">4</span> </a>
								<a data-toggle="modal" data-original-title="Help" data-placement="bottom" class="btn btn-default btn-sm" href="#helpModal"> <i class="fa fa-question"></i> </a>
							</div>
							<div class="btn-group">
								<a href="login.html" data-toggle="tooltip" data-original-title="Logout" data-placement="bottom" class="btn btn-metis-1 btn-sm"> <i class="fa fa-power-off"></i> </a>
							</div>
							<div class="btn-group">
								<a data-placement="bottom" data-original-title="Show / Hide Left" data-toggle="tooltip" class="btn btn-primary btn-sm toggle-left" id="menu-toggle"> <i class="fa fa-bars"></i> </a>
								<a data-placement="bottom" data-original-title="Show / Hide Right" data-toggle="tooltip" class="btn btn-default btn-sm toggle-right"> <span class="glyphicon glyphicon-comment"></span> </a>
							</div>
						</div>
						<div class="collapse navbar-collapse navbar-ex1-collapse">

							<!-- .nav -->
							<ul class="nav navbar-nav">
								<li>
									<%= link_to "/" do %>
									Usuario
									<%end %>

								</li>
							</ul><!-- /.nav -->
						</div>
					</div><!-- /.container-fluid -->
				</nav><!-- /.navbar -->
				<header class="head">
					<div class="search-bar">
						<form class="main-search" action="">
							<div class="input-group">
								<input type="text" class="form-control" placeholder="Live Search ...">
								<span class="input-group-btn">
									<button class="btn btn-primary btn-sm text-muted" type="button">
										<i class="fa fa-search"></i>
									</button> </span>
							</div>
						</form><!-- /.main-search -->
					</div><!-- /.search-bar -->
					<div class="main-bar">
						<h3><i class="fa fa-home"></i>&nbsp; Metis</h3>
					</div><!-- /.main-bar -->
				</header><!-- /.head -->
			</div><!-- /#top -->
			<div id="left">
				<div class="media user-media bg-dark dker">
					<div class="user-media-toggleHover">
						<span class="fa fa-user"></span>
					</div>
					<div class="user-wrapper bg-dark">
						<a class="user-link" href=""> <img class="media-object img-thumbnail user-img" alt="User Picture" src="assets/img/user.gif"> <span class="label label-danger user-label">16</span> </a>
						<div class="media-body">
							<h5 class="media-heading">Archie</h5>
							<ul class="list-unstyled user-info">
								<li>
									<a href="">Administrator</a>
								</li>
								<li>
									Last Access :
									<br>
									<small> <i class="fa fa-calendar"></i>&nbsp;16 Mar 16:32</small>
								</li>
							</ul>
						</div>
					</div>
				</div>

				<!-- #menu -->
				<ul id="menu" class="bg-dark dker">
					<li class="nav-header">
						Menu
					</li>
					<li class="nav-divider"></li>
					<li class="">
						<a href="javascript:;"> <i class="fa fa-building "></i> <span class="link-title">Cadastros</span> <span class="fa arrow"></span> </a>
						<ul>
							<li>
								<%= link_to "Clientes", clientes_path, class: "fa fa-angle-right"%>
							</li>
						</ul>
					</li>

				</ul><!-- /#menu -->
			</div><!-- /#left -->
			<div id="content">
				<div class="outer">
					<div class="inner bg-light lter">
						<div class="col-lg-12">
							<%= yield %>
						</div>
					</div>
				</div>
			</div>

		</div>

		<footer class="Footer bg-dark dker">
			<p>
				2014 &copy; Metis Bootstrap Admin Template
			</p>
		</footer><!-- /#footer -->

		<!-- #helpModal -->
		<div id="helpModal" class="modal fade">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
							&times;
						</button>
						<h4 class="modal-title">Modal title</h4>
					</div>
					<div class="modal-body">
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor
							in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">
							Close
						</button>
					</div>
				</div><!-- /.modal-content -->
			</div><!-- /.modal-dialog -->
		</div><!-- /.modal --><!-- /#helpModal -->

	</body>

</html>